[package]
name = "voronoi"
version = "0.1.0"
authors = ["Heghedus Razvan <heghedus.razvan@gmail.com>"]

[dependencies]
clap = "2"
image = "*"
rand = "0.4"
hsl = "0.1"
futures = "0.1"
futures-cpupool = "0.1"
